### ISSUE TITLE
Where is the BigMap implemented?

### ISSUE THREAD

**Issue by oexza** [dfinity/cancan#24]
The doc site states "BigMap provides a simple, plug-in library for building scalable applications using key-value storage on the Internet Computer. By using the BigMap library as a back-end service, the CanCan sample application can dynamically chunk, serialize, and distribute data to multiple canisters."

It futher stated "Although the BigMap service you see in the CanCan repository is written in Rust"

Where is this BigMap backend service implemented? How is it imported and used? I tried to peruse the code but found nothing.  Kindly point me in the right direction. Apologies if this is the wrong place to ask.

Cheers.

**Comment by lsgunnlsgunn** [comment]
@oexza, thanks for your interest in the project. BigMap was originally intended to be available as an open source library along with the CanCan sample app. During the re-architecture of the CanCan app, however, the implementation of BigMap was shelved for technical reasons. We do plan to update and release BigMap as open source "soon" but it has lower priority than some other work. Apologies for misleading you in the doc!  We expected the library to be publicly available and didn't get around to revising that section when plans changed. We'll remove that section then restore it when the BigMap repo is open source.

**Comment by taylorham** [comment]
@oexza To expound on @lsgunnlsgunn's answer, the effort to complete BigMap isn't scheduled to be fully up to speed again until around September at the earliest, but we'll communicate as openly and often about this as possible.

Since there's no action we can take in the near future I'll go ahead and close this issue. Let us know if you have any other questions or roadblocks.

Watch for further news [on our blog](https://medium.com/dfinity), [our forum](https://forum.dfinity.org), and [our developer documentation](https://sdk.dfinity.org), and thanks for following the project!

**Comment by oexza** [comment]
Ah! I thought it was me not looking in the right place. thanks @lsgunnlsgunn and @taylorham . What is an alternative for data intensive applications? My goal here is to build an event store on the IC similar to [https://www.eventstore.com/eventstoredb](url) .

**Comment by valerobles** [comment]
Hey everyone, I was wondering what the current update is on BigMap. Is it available to use as library or is there another solution being used for scalable dapps? Cheers

**Comment by ggreif** [comment]
@valerobles It is probably better to ask at https://forum.dfinity.org, as cancan is pretty much defunct nowadays.
